/* Marketing content & UI strings for the conversion-optimized homepage.
   Kept separate from App.js to keep the main file manageable. 5 languages. */

/* ---- UI strings (merged into t() as fallback) ---- */
export const MT = {
  it: {
    hero_h1a: "Analizza i tuoi documenti in pochi secondi.",
    hero_h1b: "L'AI trova dati, errori e rischi prima di te.",
    hero_h1a_b: "L'AI che trova errori e rischi nei tuoi documenti.",
    hero_h1b_b: "Analisi automatica e strutturata in pochi secondi.",
    hero_sub2: "Fatture, F24, contratti, visure, buste paga e altri documenti. Carica un file e ottieni un'analisi strutturata e intelligente in pochi secondi.",
    cta_try: "Analizza gratis il tuo primo documento",
    cta_try_short: "Prova gratis",
    cta_how: "Scopri come funziona",
    free_note: "3 crediti gratuiti · Nessuna carta richiesta",
    ai_engine: "Motore AI",
    analyzed_by: "Analizzato con",
    claude_hint: "Consigliato per contratti e testi lunghi",
    gemini_hint: "Veloce su fatture e documenti strutturati",
    compare_btn: "Confronta con",
    comparing: "Confronto in corso…",
    compare_title: "Confronto tra modelli",
    compare_note: "Analizza lo stesso documento con l'altro modello (usa 1 credito)",
    nav_history: "Storico",
    history_title: "Storico analisi",
    history_empty: "Non hai ancora nessuna analisi.",
    hist_fields: "campi",
    hist_reopen: "Riapri",
    rating_line: "4,9/5 · 482+ recensioni verificate",
    trusted_by: "Scelto da commercialisti, avvocati, notai e responsabili HR",
    how_title: "Come funziona",
    how_sub: "Dal documento al risultato in 4 semplici passaggi.",
    rf_kicker: "RED-FLAG AI",
    rf_title: "L'AI che trova ciò che potresti non notare.",
    rf_sub: "Un secondo cervello che controlla ogni documento e segnala automaticamente i rischi prima che diventino un problema.",
    rf_finds: "Cosa individua Red-Flag AI",
    cop_kicker: "COPILOT",
    cop_title: "Fai domande direttamente al tuo documento.",
    cop_sub: "Non un semplice chatbot: un assistente collegato al documento che hai appena analizzato. Chiedi, ottieni risposte immediate.",
    cop_cta: "Prova Copilot",
    cop_examples_ttl: "Esempi di domande",
    doc_title: "Tutti i tuoi documenti, una sola piattaforma",
    doc_sub: "DocuAnalytics riconosce e analizza automaticamente i documenti che usi ogni giorno.",
    sct_title: "Pensato per il tuo lavoro",
    sct_sub: "Ogni professione ha le sue esigenze. DocuAnalytics si adatta alla tua.",
    sct_cta: "Prova gratis",
    secp_kicker: "SICUREZZA & PRIVACY",
    secp_title: "I tuoi documenti, la tua privacy.",
    secp_sub: "Carichi documenti sensibili. Ecco cosa succede — e cosa non succede — ai tuoi file.",
    trial_title: "Prova DocuAnalytics gratuitamente",
    trial_l1: "3 crediti inclusi",
    trial_l2: "Nessuna carta richiesta",
    trial_l3: "Carica il tuo primo documento e scopri cosa può fare l'AI.",
    trial_cta: "Inizia gratis",
    price_title: "Prezzi semplici e trasparenti",
    price_sub: "Inizi gratis con 3 crediti. Poi paghi solo ciò che usi: 1 credito = 1 analisi.",
    price_packs: "Pacchetti crediti (pagamento singolo)",
    price_subs: "Abbonamenti studio (rinnovo mensile)",
    price_buy: "Acquista crediti",
    price_all: "Vedi tutti i piani e i metodi di pagamento",
    price_recommended: "CONSIGLIATO",
    final_title: "Pronto a risparmiare tempo sui tuoi documenti?",
    final_sub: "Carica il tuo primo documento adesso: bastano pochi secondi e non serve la carta di credito.",
    wow_done: "Analisi completata",
    wow_fields: "dati estratti",
    wow_checks: "controlli eseguiti",
    after_title: "Vuoi analizzare altri documenti?",
    after_left: "Ti rimangono {n} crediti gratuiti.",
    after_out: "Hai terminato i crediti gratuiti.",
    after_again: "Analizza un altro documento",
    nav_how: "Come funziona",
    nav_price: "Prezzi",
    contact: "Contatti",
    sl_for: "DocuAnalytics per", sl_usecases: "Casi d'uso", sl_benefits: "Vantaggi", sl_example: "Esempio pratico", sl_back: "Torna alla home", sl_other: "Esplora altri settori",
  },
  en: {
    hero_h1a: "Analyze your documents in seconds.",
    hero_h1b: "AI finds data, errors and risks before you do.",
    hero_h1a_b: "The AI that finds errors and risks in your documents.",
    hero_h1b_b: "Automatic, structured analysis in seconds.",
    hero_sub2: "Invoices, tax forms, contracts, company records, payslips and more. Upload a file and get a structured, intelligent analysis in seconds.",
    cta_try: "Analyze your first document for free",
    cta_try_short: "Try for free",
    cta_how: "See how it works",
    free_note: "3 free credits · No card required",
    ai_engine: "AI engine",
    analyzed_by: "Analyzed with",
    claude_hint: "Recommended for contracts and long texts",
    gemini_hint: "Fast on invoices and structured documents",
    compare_btn: "Compare with",
    comparing: "Comparing…",
    compare_title: "Model comparison",
    compare_note: "Analyze the same document with the other model (uses 1 credit)",
    nav_history: "History",
    history_title: "Analysis history",
    history_empty: "You have no analyses yet.",
    hist_fields: "fields",
    hist_reopen: "Reopen",
    rating_line: "4.9/5 · 482+ verified reviews",
    trusted_by: "Chosen by accountants, lawyers, notaries and HR managers",
    how_title: "How it works",
    how_sub: "From document to result in 4 simple steps.",
    rf_kicker: "RED-FLAG AI",
    rf_title: "The AI that finds what you might miss.",
    rf_sub: "A second brain that checks every document and automatically flags risks before they become a problem.",
    rf_finds: "What Red-Flag AI detects",
    cop_kicker: "COPILOT",
    cop_title: "Ask questions straight to your document.",
    cop_sub: "Not a plain chatbot: an assistant connected to the document you just analyzed. Ask, get instant answers.",
    cop_cta: "Try Copilot",
    cop_examples_ttl: "Example questions",
    doc_title: "All your documents, one platform",
    doc_sub: "DocuAnalytics automatically recognizes and analyzes the documents you use every day.",
    sct_title: "Built for your work",
    sct_sub: "Every profession has its own needs. DocuAnalytics adapts to yours.",
    sct_cta: "Try for free",
    secp_kicker: "SECURITY & PRIVACY",
    secp_title: "Your documents, your privacy.",
    secp_sub: "You upload sensitive documents. Here's what happens — and what doesn't — to your files.",
    trial_title: "Try DocuAnalytics for free",
    trial_l1: "3 credits included",
    trial_l2: "No card required",
    trial_l3: "Upload your first document and see what the AI can do.",
    trial_cta: "Start free",
    price_title: "Simple, transparent pricing",
    price_sub: "Start free with 3 credits. Then pay only for what you use: 1 credit = 1 analysis.",
    price_packs: "Credit packs (one-time payment)",
    price_subs: "Firm subscriptions (monthly renewal)",
    price_buy: "Buy credits",
    price_all: "See all plans and payment methods",
    price_recommended: "RECOMMENDED",
    final_title: "Ready to save time on your documents?",
    final_sub: "Upload your first document now: it takes seconds and no credit card is needed.",
    wow_done: "Analysis complete",
    wow_fields: "data extracted",
    wow_checks: "checks performed",
    after_title: "Want to analyze more documents?",
    after_left: "You have {n} free credits left.",
    after_out: "You've used up your free credits.",
    after_again: "Analyze another document",
    nav_how: "How it works",
    nav_price: "Pricing",
    contact: "Contact",
    sl_for: "DocuAnalytics for", sl_usecases: "Use cases", sl_benefits: "Benefits", sl_example: "In practice", sl_back: "Back to home", sl_other: "Explore other sectors",
  },
  es: {
    hero_h1a: "Analiza tus documentos en segundos.",
    hero_h1b: "La IA encuentra datos, errores y riesgos antes que tú.",
    hero_h1a_b: "La IA que encuentra errores y riesgos en tus documentos.",
    hero_h1b_b: "Análisis automático y estructurado en segundos.",
    hero_sub2: "Facturas, modelos fiscales, contratos, registros mercantiles, nóminas y más. Sube un archivo y obtén un análisis estructurado e inteligente en segundos.",
    cta_try: "Analiza tu primer documento gratis",
    cta_try_short: "Prueba gratis",
    cta_how: "Descubre cómo funciona",
    free_note: "3 créditos gratis · Sin tarjeta",
    ai_engine: "Motor de IA",
    analyzed_by: "Analizado con",
    claude_hint: "Recomendado para contratos y textos largos",
    gemini_hint: "Rápido con facturas y documentos estructurados",
    compare_btn: "Comparar con",
    comparing: "Comparando…",
    compare_title: "Comparación de modelos",
    compare_note: "Analiza el mismo documento con el otro modelo (usa 1 crédito)",
    nav_history: "Historial",
    history_title: "Historial de análisis",
    history_empty: "Aún no tienes análisis.",
    hist_fields: "campos",
    hist_reopen: "Reabrir",
    rating_line: "4,9/5 · 482+ reseñas verificadas",
    trusted_by: "Elegido por asesores, abogados, notarios y responsables de RR. HH.",
    how_title: "Cómo funciona",
    how_sub: "Del documento al resultado en 4 sencillos pasos.",
    rf_kicker: "ALERTAS IA",
    rf_title: "La IA que encuentra lo que podrías no notar.",
    rf_sub: "Un segundo cerebro que revisa cada documento y señala automáticamente los riesgos antes de que sean un problema.",
    rf_finds: "Qué detecta el detector de alertas IA",
    cop_kicker: "COPILOT",
    cop_title: "Haz preguntas directamente a tu documento.",
    cop_sub: "No es un simple chatbot: un asistente conectado al documento que acabas de analizar. Pregunta y obtén respuestas al instante.",
    cop_cta: "Prueba Copilot",
    cop_examples_ttl: "Ejemplos de preguntas",
    doc_title: "Todos tus documentos, una sola plataforma",
    doc_sub: "DocuAnalytics reconoce y analiza automáticamente los documentos que usas cada día.",
    sct_title: "Pensado para tu trabajo",
    sct_sub: "Cada profesión tiene sus necesidades. DocuAnalytics se adapta a la tuya.",
    sct_cta: "Prueba gratis",
    secp_kicker: "SEGURIDAD Y PRIVACIDAD",
    secp_title: "Tus documentos, tu privacidad.",
    secp_sub: "Subes documentos sensibles. Esto es lo que pasa — y lo que no — con tus archivos.",
    trial_title: "Prueba DocuAnalytics gratis",
    trial_l1: "3 créditos incluidos",
    trial_l2: "Sin tarjeta",
    trial_l3: "Sube tu primer documento y descubre lo que puede hacer la IA.",
    trial_cta: "Empieza gratis",
    price_title: "Precios simples y transparentes",
    price_sub: "Empieza gratis con 3 créditos. Luego pagas solo lo que usas: 1 crédito = 1 análisis.",
    price_packs: "Packs de créditos (pago único)",
    price_subs: "Suscripciones de despacho (renovación mensual)",
    price_buy: "Comprar créditos",
    price_all: "Ver todos los planes y métodos de pago",
    price_recommended: "RECOMENDADO",
    final_title: "¿List@ para ahorrar tiempo con tus documentos?",
    final_sub: "Sube tu primer documento ahora: solo tarda unos segundos y no necesitas tarjeta.",
    wow_done: "Análisis completado",
    wow_fields: "datos extraídos",
    wow_checks: "controles realizados",
    after_title: "¿Quieres analizar más documentos?",
    after_left: "Te quedan {n} créditos gratis.",
    after_out: "Has agotado tus créditos gratis.",
    after_again: "Analizar otro documento",
    nav_how: "Cómo funciona",
    nav_price: "Precios",
    contact: "Contacto",
    sl_for: "DocuAnalytics para", sl_usecases: "Casos de uso", sl_benefits: "Ventajas", sl_example: "En la práctica", sl_back: "Volver al inicio", sl_other: "Explora otros sectores",
  },
  de: {
    hero_h1a: "Analysieren Sie Ihre Dokumente in Sekunden.",
    hero_h1b: "Die KI findet Daten, Fehler und Risiken vor Ihnen.",
    hero_h1a_b: "Die KI, die Fehler und Risiken in Ihren Dokumenten findet.",
    hero_h1b_b: "Automatische, strukturierte Analyse in Sekunden.",
    hero_sub2: "Rechnungen, Steuerformulare, Verträge, Registerauszüge, Gehaltsabrechnungen und mehr. Datei hochladen und in Sekunden eine strukturierte, intelligente Analyse erhalten.",
    cta_try: "Erstes Dokument kostenlos analysieren",
    cta_try_short: "Kostenlos testen",
    cta_how: "So funktioniert's",
    free_note: "3 Gratis-Guthaben · Keine Karte nötig",
    ai_engine: "KI-Engine",
    analyzed_by: "Analysiert mit",
    claude_hint: "Empfohlen für Verträge und lange Texte",
    gemini_hint: "Schnell bei Rechnungen und strukturierten Dokumenten",
    compare_btn: "Vergleichen mit",
    comparing: "Vergleiche…",
    compare_title: "Modellvergleich",
    compare_note: "Dasselbe Dokument mit dem anderen Modell analysieren (1 Guthaben)",
    nav_history: "Verlauf",
    history_title: "Analyseverlauf",
    history_empty: "Sie haben noch keine Analysen.",
    hist_fields: "Felder",
    hist_reopen: "Öffnen",
    rating_line: "4,9/5 · 482+ verifizierte Bewertungen",
    trusted_by: "Gewählt von Steuerberatern, Anwälten, Notaren und HR-Verantwortlichen",
    how_title: "So funktioniert's",
    how_sub: "Vom Dokument zum Ergebnis in 4 einfachen Schritten.",
    rf_kicker: "RED-FLAG KI",
    rf_title: "Die KI, die findet, was Sie übersehen könnten.",
    rf_sub: "Ein zweites Gehirn, das jedes Dokument prüft und Risiken automatisch meldet, bevor sie zum Problem werden.",
    rf_finds: "Was der Red-Flag-Detektor erkennt",
    cop_kicker: "COPILOT",
    cop_title: "Stellen Sie Fragen direkt an Ihr Dokument.",
    cop_sub: "Kein einfacher Chatbot: ein Assistent, der mit dem gerade analysierten Dokument verbunden ist. Fragen, sofort Antworten erhalten.",
    cop_cta: "Copilot testen",
    cop_examples_ttl: "Beispielfragen",
    doc_title: "Alle Ihre Dokumente, eine Plattform",
    doc_sub: "DocuAnalytics erkennt und analysiert automatisch die Dokumente, die Sie täglich nutzen.",
    sct_title: "Für Ihre Arbeit gemacht",
    sct_sub: "Jeder Beruf hat eigene Anforderungen. DocuAnalytics passt sich Ihrem an.",
    sct_cta: "Kostenlos testen",
    secp_kicker: "SICHERHEIT & DATENSCHUTZ",
    secp_title: "Ihre Dokumente, Ihr Datenschutz.",
    secp_sub: "Sie laden sensible Dokumente hoch. Das passiert — und das passiert nicht — mit Ihren Dateien.",
    trial_title: "DocuAnalytics kostenlos testen",
    trial_l1: "3 Guthaben inklusive",
    trial_l2: "Keine Karte nötig",
    trial_l3: "Laden Sie Ihr erstes Dokument hoch und entdecken Sie, was die KI kann.",
    trial_cta: "Kostenlos starten",
    price_title: "Einfache, transparente Preise",
    price_sub: "Kostenlos mit 3 Guthaben starten. Danach zahlen Sie nur, was Sie nutzen: 1 Guthaben = 1 Analyse.",
    price_packs: "Guthaben-Pakete (Einmalzahlung)",
    price_subs: "Kanzlei-Abos (monatliche Verlängerung)",
    price_buy: "Guthaben kaufen",
    price_all: "Alle Pläne und Zahlungsmethoden ansehen",
    price_recommended: "EMPFOHLEN",
    final_title: "Bereit, Zeit bei Ihren Dokumenten zu sparen?",
    final_sub: "Laden Sie jetzt Ihr erstes Dokument hoch: dauert Sekunden, keine Kreditkarte nötig.",
    wow_done: "Analyse abgeschlossen",
    wow_fields: "Daten extrahiert",
    wow_checks: "Prüfungen durchgeführt",
    after_title: "Möchten Sie weitere Dokumente analysieren?",
    after_left: "Sie haben noch {n} Gratis-Guthaben.",
    after_out: "Sie haben Ihre Gratis-Guthaben aufgebraucht.",
    after_again: "Weiteres Dokument analysieren",
    nav_how: "So funktioniert's",
    nav_price: "Preise",
    contact: "Kontakt",
    sl_for: "DocuAnalytics für", sl_usecases: "Anwendungsfälle", sl_benefits: "Vorteile", sl_example: "In der Praxis", sl_back: "Zurück zur Startseite", sl_other: "Weitere Branchen entdecken",
  },
  fr: {
    hero_h1a: "Analysez vos documents en quelques secondes.",
    hero_h1b: "L'IA trouve données, erreurs et risques avant vous.",
    hero_h1a_b: "L'IA qui trouve les erreurs et les risques dans vos documents.",
    hero_h1b_b: "Analyse automatique et structurée en quelques secondes.",
    hero_sub2: "Factures, formulaires fiscaux, contrats, extraits Kbis, bulletins de paie et plus. Importez un fichier et obtenez une analyse structurée et intelligente en quelques secondes.",
    cta_try: "Analysez votre premier document gratuitement",
    cta_try_short: "Essayer gratuitement",
    cta_how: "Découvrez comment ça marche",
    free_note: "3 crédits gratuits · Sans carte",
    ai_engine: "Moteur IA",
    analyzed_by: "Analysé avec",
    claude_hint: "Recommandé pour les contrats et textes longs",
    gemini_hint: "Rapide sur les factures et documents structurés",
    compare_btn: "Comparer avec",
    comparing: "Comparaison…",
    compare_title: "Comparaison des modèles",
    compare_note: "Analyser le même document avec l'autre modèle (utilise 1 crédit)",
    nav_history: "Historique",
    history_title: "Historique des analyses",
    history_empty: "Vous n'avez pas encore d'analyses.",
    hist_fields: "champs",
    hist_reopen: "Rouvrir",
    rating_line: "4,9/5 · 482+ avis vérifiés",
    trusted_by: "Choisi par experts-comptables, avocats, notaires et responsables RH",
    how_title: "Comment ça marche",
    how_sub: "Du document au résultat en 4 étapes simples.",
    rf_kicker: "ALERTES IA",
    rf_title: "L'IA qui trouve ce que vous pourriez manquer.",
    rf_sub: "Un second cerveau qui vérifie chaque document et signale automatiquement les risques avant qu'ils ne deviennent un problème.",
    rf_finds: "Ce que le détecteur d'alertes IA repère",
    cop_kicker: "COPILOT",
    cop_title: "Posez des questions directement à votre document.",
    cop_sub: "Pas un simple chatbot : un assistant connecté au document que vous venez d'analyser. Demandez, obtenez des réponses immédiates.",
    cop_cta: "Essayer Copilot",
    cop_examples_ttl: "Exemples de questions",
    doc_title: "Tous vos documents, une seule plateforme",
    doc_sub: "DocuAnalytics reconnaît et analyse automatiquement les documents que vous utilisez chaque jour.",
    sct_title: "Conçu pour votre métier",
    sct_sub: "Chaque profession a ses besoins. DocuAnalytics s'adapte au vôtre.",
    sct_cta: "Essayer gratuitement",
    secp_kicker: "SÉCURITÉ & CONFIDENTIALITÉ",
    secp_title: "Vos documents, votre confidentialité.",
    secp_sub: "Vous importez des documents sensibles. Voici ce qui arrive — et n'arrive pas — à vos fichiers.",
    trial_title: "Essayez DocuAnalytics gratuitement",
    trial_l1: "3 crédits inclus",
    trial_l2: "Sans carte",
    trial_l3: "Importez votre premier document et découvrez ce que l'IA peut faire.",
    trial_cta: "Commencer gratuitement",
    price_title: "Des prix simples et transparents",
    price_sub: "Commencez gratuitement avec 3 crédits. Ensuite, payez seulement ce que vous utilisez : 1 crédit = 1 analyse.",
    price_packs: "Packs de crédits (paiement unique)",
    price_subs: "Abonnements cabinet (renouvellement mensuel)",
    price_buy: "Acheter des crédits",
    price_all: "Voir tous les plans et moyens de paiement",
    price_recommended: "RECOMMANDÉ",
    final_title: "Prêt à gagner du temps sur vos documents ?",
    final_sub: "Importez votre premier document maintenant : quelques secondes suffisent, sans carte bancaire.",
    wow_done: "Analyse terminée",
    wow_fields: "données extraites",
    wow_checks: "contrôles effectués",
    after_title: "Envie d'analyser d'autres documents ?",
    after_left: "Il vous reste {n} crédits gratuits.",
    after_out: "Vous avez épuisé vos crédits gratuits.",
    after_again: "Analyser un autre document",
    nav_how: "Comment ça marche",
    nav_price: "Tarifs",
    contact: "Contact",
    sl_for: "DocuAnalytics pour", sl_usecases: "Cas d'usage", sl_benefits: "Avantages", sl_example: "En pratique", sl_back: "Retour à l'accueil", sl_other: "Explorer d'autres secteurs",
  },
};

/* ---- Marketing arrays (used via useMark()) ---- */
export const MARK = {
  it: {
    benefits: [
      { icon: "Clock", t: "Risparmi tempo", d: "Controlli in secondi ciò che richiederebbe minuti di lettura manuale." },
      { icon: "AlertTriangle", t: "Meno errori", d: "L'AI verifica quadrature e coerenza dei dati al posto tuo." },
      { icon: "Search", t: "Trovi le anomalie", d: "Rischi, clausole e incongruenze evidenziati automaticamente." },
      { icon: "Rocket", t: "Più produttività", d: "Un flusso di controllo documentale rapido, ripetibile e affidabile." },
    ],
    how: [
      { n: "01", icon: "Upload", t: "Carica", d: "Carica il tuo documento (PDF, JPG o PNG)." },
      { n: "02", icon: "Zap", t: "Analizza", d: "L'intelligenza artificiale analizza automaticamente il contenuto." },
      { n: "03", icon: "Search", t: "Scopri", d: "Visualizza dati, anomalie, informazioni importanti e possibili rischi." },
      { n: "04", icon: "Rocket", t: "Agisci", d: "Esporta i risultati, usa il Copilot o approfondisci l'analisi." },
    ],
    rfFinds: ["Anomalie e incongruenze", "Clausole problematiche", "IBAN esteri sospetti", "Squadrature negli importi", "Scadenze e preavvisi critici", "Elementi di rischio da approfondire"],
    copExamples: ["Qual è l'importo totale?", "Ci sono anomalie?", "Quali sono le clausole più importanti?", "Trova l'IBAN.", "Riassumi questo documento.", "Quali elementi dovrei controllare?"],
    docs: [
      { key: "fattura", t: "Fatture", d: "Dati, importi, IVA e possibili anomalie estratti automaticamente." },
      { key: "f24", t: "F24", d: "Codici tributo, scadenze e quadratura Debito/Credito/Saldo." },
      { key: "contratto", t: "Contratti", d: "Clausole, parti, durata e possibili elementi da approfondire." },
      { key: "visura", t: "Visure", d: "REA, soci, amministratori e verifiche antiriciclaggio (KYC/AML)." },
      { key: "busta_paga", t: "Buste paga", d: "Lordo, contributi, IRPEF, netto e TFR maturato." },
      { key: "altri", t: "Altri documenti", d: "Estrazione dati e audit anche su documenti generici." },
    ],
    sectors: [
      { slug: "commercialisti", icon: "Landmark", t: "Commercialisti", d: "Controlla fatture, F24 e visure in secondi, senza inserimenti manuali." },
      { slug: "avvocati", icon: "Scale", t: "Avvocati", d: "Individua rapidamente clausole, scadenze e criticità nei contratti." },
      { slug: "notai", icon: "FileSignature", t: "Notai", d: "Estrai dati societari e verifica visure e documenti in un attimo." },
      { slug: "cfo", icon: "TrendingUp", t: "CFO & Finance", d: "Verifica importi, quadrature e coerenza dei dati contabili." },
      { slug: "hr", icon: "Users", t: "HR", d: "Analizza buste paga e documenti del personale in pochi secondi." },
      { slug: "aziende", icon: "Briefcase", t: "Aziende & Professionisti", d: "Automatizza il controllo di ogni documento che gestisci." },
    ],
    security: [
      { icon: "Ban", t: "Nessun documento memorizzato", d: "I file non vengono conservati sui nostri server." },
      { icon: "Zap", t: "Elaborazione in tempo reale", d: "Ogni documento è analizzato al volo, senza archiviazione." },
      { icon: "Trash2", t: "Cancellazione immediata", d: "Il file viene eliminato appena l'analisi è completata." },
      { icon: "BadgeCheck", t: "Conforme al GDPR", d: "Trattamento dei dati conforme al Regolamento europeo." },
      { icon: "Lock", t: "Trasmissione cifrata HTTPS", d: "I dati viaggiano sempre su connessione protetta." },
      { icon: "Server", t: "Server in UE", d: "L'elaborazione avviene su infrastruttura nell'Unione Europea." },
    ],
  },
  en: {
    benefits: [
      { icon: "Clock", t: "Save time", d: "Check in seconds what would take minutes of manual reading." },
      { icon: "AlertTriangle", t: "Fewer errors", d: "The AI verifies reconciliations and data consistency for you." },
      { icon: "Search", t: "Spot anomalies", d: "Risks, clauses and inconsistencies highlighted automatically." },
      { icon: "Rocket", t: "More productivity", d: "A fast, repeatable and reliable document-checking workflow." },
    ],
    how: [
      { n: "01", icon: "Upload", t: "Upload", d: "Upload your document (PDF, JPG or PNG)." },
      { n: "02", icon: "Zap", t: "Analyze", d: "Artificial intelligence automatically analyzes the content." },
      { n: "03", icon: "Search", t: "Discover", d: "See data, anomalies, key information and possible risks." },
      { n: "04", icon: "Rocket", t: "Act", d: "Export results, use the Copilot or dig deeper into the analysis." },
    ],
    rfFinds: ["Anomalies and inconsistencies", "Problematic clauses", "Suspicious foreign IBAN", "Amount mismatches", "Critical deadlines and notices", "Risk items to review"],
    copExamples: ["What's the total amount?", "Are there any anomalies?", "What are the most important clauses?", "Find the IBAN.", "Summarize this document.", "What items should I check?"],
    docs: [
      { key: "fattura", t: "Invoices", d: "Data, amounts, VAT and possible anomalies extracted automatically." },
      { key: "f24", t: "Tax forms", d: "Tax codes, due dates and Debit/Credit/Balance reconciliation." },
      { key: "contratto", t: "Contracts", d: "Clauses, parties, duration and possible items to review." },
      { key: "visura", t: "Company records", d: "Registration, shareholders, directors and AML/KYC checks." },
      { key: "busta_paga", t: "Payslips", d: "Gross, contributions, tax, net and accrued severance." },
      { key: "altri", t: "Other documents", d: "Data extraction and audit on generic documents too." },
    ],
    sectors: [
      { slug: "commercialisti", icon: "Landmark", t: "Accountants", d: "Check invoices, tax forms and records in seconds, no manual entry." },
      { slug: "avvocati", icon: "Scale", t: "Lawyers", d: "Quickly spot clauses, deadlines and issues in contracts." },
      { slug: "notai", icon: "FileSignature", t: "Notaries", d: "Extract company data and verify records in an instant." },
      { slug: "cfo", icon: "TrendingUp", t: "CFO & Finance", d: "Verify amounts, reconciliations and accounting data consistency." },
      { slug: "hr", icon: "Users", t: "HR", d: "Analyze payslips and personnel documents in seconds." },
      { slug: "aziende", icon: "Briefcase", t: "Businesses & Pros", d: "Automate the review of every document you handle." },
    ],
    security: [
      { icon: "Ban", t: "No document stored", d: "Files are not kept on our servers." },
      { icon: "Zap", t: "Real-time processing", d: "Every document is analyzed on the fly, with no archiving." },
      { icon: "Trash2", t: "Instant deletion", d: "The file is deleted as soon as the analysis is complete." },
      { icon: "BadgeCheck", t: "GDPR compliant", d: "Data processing compliant with the EU regulation." },
      { icon: "Lock", t: "Encrypted HTTPS", d: "Data always travels over a secure connection." },
      { icon: "Server", t: "EU servers", d: "Processing takes place on infrastructure within the EU." },
    ],
  },
  es: {
    benefits: [
      { icon: "Clock", t: "Ahorra tiempo", d: "Revisa en segundos lo que llevaría minutos de lectura manual." },
      { icon: "AlertTriangle", t: "Menos errores", d: "La IA verifica cuadres y coherencia de los datos por ti." },
      { icon: "Search", t: "Detecta anomalías", d: "Riesgos, cláusulas e incoherencias resaltados automáticamente." },
      { icon: "Rocket", t: "Más productividad", d: "Un flujo de control documental rápido, repetible y fiable." },
    ],
    how: [
      { n: "01", icon: "Upload", t: "Sube", d: "Sube tu documento (PDF, JPG o PNG)." },
      { n: "02", icon: "Zap", t: "Analiza", d: "La inteligencia artificial analiza automáticamente el contenido." },
      { n: "03", icon: "Search", t: "Descubre", d: "Visualiza datos, anomalías, información importante y posibles riesgos." },
      { n: "04", icon: "Rocket", t: "Actúa", d: "Exporta los resultados, usa el Copilot o profundiza en el análisis." },
    ],
    rfFinds: ["Anomalías e incoherencias", "Cláusulas problemáticas", "IBAN extranjeros sospechosos", "Descuadres en los importes", "Vencimientos y preavisos críticos", "Elementos de riesgo a revisar"],
    copExamples: ["¿Cuál es el importe total?", "¿Hay anomalías?", "¿Cuáles son las cláusulas más importantes?", "Encuentra el IBAN.", "Resume este documento.", "¿Qué elementos debería revisar?"],
    docs: [
      { key: "fattura", t: "Facturas", d: "Datos, importes, IVA y posibles anomalías extraídos automáticamente." },
      { key: "f24", t: "Modelos fiscales", d: "Códigos, vencimientos y cuadre Debe/Haber/Saldo." },
      { key: "contratto", t: "Contratos", d: "Cláusulas, partes, duración y posibles elementos a revisar." },
      { key: "visura", t: "Registros mercantiles", d: "Datos registrales, socios, administradores y AML/KYC." },
      { key: "busta_paga", t: "Nóminas", d: "Bruto, cotizaciones, IRPF, neto y finiquito acumulado." },
      { key: "altri", t: "Otros documentos", d: "Extracción de datos y auditoría también en documentos genéricos." },
    ],
    sectors: [
      { slug: "commercialisti", icon: "Landmark", t: "Asesores", d: "Revisa facturas, modelos y registros en segundos, sin entradas manuales." },
      { slug: "avvocati", icon: "Scale", t: "Abogados", d: "Detecta rápidamente cláusulas, plazos y problemas en contratos." },
      { slug: "notai", icon: "FileSignature", t: "Notarios", d: "Extrae datos societarios y verifica documentos al instante." },
      { slug: "cfo", icon: "TrendingUp", t: "CFO y Finanzas", d: "Verifica importes, cuadres y coherencia de los datos contables." },
      { slug: "hr", icon: "Users", t: "RR. HH.", d: "Analiza nóminas y documentos del personal en segundos." },
      { slug: "aziende", icon: "Briefcase", t: "Empresas y Pros", d: "Automatiza la revisión de cada documento que gestionas." },
    ],
    security: [
      { icon: "Ban", t: "Ningún documento almacenado", d: "Los archivos no se conservan en nuestros servidores." },
      { icon: "Zap", t: "Procesamiento en tiempo real", d: "Cada documento se analiza al vuelo, sin archivado." },
      { icon: "Trash2", t: "Eliminación inmediata", d: "El archivo se elimina en cuanto termina el análisis." },
      { icon: "BadgeCheck", t: "Conforme al RGPD", d: "Tratamiento de datos conforme al reglamento europeo." },
      { icon: "Lock", t: "HTTPS cifrado", d: "Los datos siempre viajan por conexión segura." },
      { icon: "Server", t: "Servidores en la UE", d: "El procesamiento se realiza en infraestructura de la UE." },
    ],
  },
  de: {
    benefits: [
      { icon: "Clock", t: "Zeit sparen", d: "Prüfen Sie in Sekunden, was Minuten manuellen Lesens kostet." },
      { icon: "AlertTriangle", t: "Weniger Fehler", d: "Die KI prüft Abgleiche und Datenkonsistenz für Sie." },
      { icon: "Search", t: "Anomalien erkennen", d: "Risiken, Klauseln und Widersprüche automatisch hervorgehoben." },
      { icon: "Rocket", t: "Mehr Produktivität", d: "Ein schneller, wiederholbarer und zuverlässiger Prüf-Workflow." },
    ],
    how: [
      { n: "01", icon: "Upload", t: "Hochladen", d: "Laden Sie Ihr Dokument hoch (PDF, JPG oder PNG)." },
      { n: "02", icon: "Zap", t: "Analysieren", d: "Die künstliche Intelligenz analysiert den Inhalt automatisch." },
      { n: "03", icon: "Search", t: "Entdecken", d: "Sehen Sie Daten, Anomalien, wichtige Infos und mögliche Risiken." },
      { n: "04", icon: "Rocket", t: "Handeln", d: "Ergebnisse exportieren, Copilot nutzen oder Analyse vertiefen." },
    ],
    rfFinds: ["Anomalien und Widersprüche", "Problematische Klauseln", "Verdächtige ausländische IBAN", "Abweichungen bei Beträgen", "Kritische Fristen und Hinweise", "Zu prüfende Risikopunkte"],
    copExamples: ["Wie hoch ist der Gesamtbetrag?", "Gibt es Anomalien?", "Was sind die wichtigsten Klauseln?", "Finde die IBAN.", "Fasse dieses Dokument zusammen.", "Welche Punkte sollte ich prüfen?"],
    docs: [
      { key: "fattura", t: "Rechnungen", d: "Daten, Beträge, USt. und mögliche Anomalien automatisch extrahiert." },
      { key: "f24", t: "Steuerformulare", d: "Codes, Fristen und Soll/Haben/Saldo-Abgleich." },
      { key: "contratto", t: "Verträge", d: "Klauseln, Parteien, Laufzeit und zu prüfende Punkte." },
      { key: "visura", t: "Registerauszüge", d: "Registerdaten, Gesellschafter, Geschäftsführer und AML/KYC." },
      { key: "busta_paga", t: "Abrechnungen", d: "Brutto, Beiträge, Steuer, Netto und aufgelaufene Abfindung." },
      { key: "altri", t: "Weitere Dokumente", d: "Datenextraktion und Audit auch bei generischen Dokumenten." },
    ],
    sectors: [
      { slug: "commercialisti", icon: "Landmark", t: "Steuerberater", d: "Rechnungen, Formulare und Auszüge in Sekunden prüfen, ohne Handeingabe." },
      { slug: "avvocati", icon: "Scale", t: "Anwälte", d: "Klauseln, Fristen und Probleme in Verträgen schnell erkennen." },
      { slug: "notai", icon: "FileSignature", t: "Notare", d: "Gesellschaftsdaten extrahieren und Dokumente sofort prüfen." },
      { slug: "cfo", icon: "TrendingUp", t: "CFO & Finance", d: "Beträge, Abgleiche und Konsistenz der Buchhaltungsdaten prüfen." },
      { slug: "hr", icon: "Users", t: "HR", d: "Gehaltsabrechnungen und Personaldokumente in Sekunden analysieren." },
      { slug: "aziende", icon: "Briefcase", t: "Unternehmen & Profis", d: "Die Prüfung jedes Dokuments automatisieren." },
    ],
    security: [
      { icon: "Ban", t: "Kein Dokument gespeichert", d: "Dateien werden nicht auf unseren Servern aufbewahrt." },
      { icon: "Zap", t: "Echtzeit-Verarbeitung", d: "Jedes Dokument wird sofort analysiert, ohne Archivierung." },
      { icon: "Trash2", t: "Sofortige Löschung", d: "Die Datei wird gelöscht, sobald die Analyse abgeschlossen ist." },
      { icon: "BadgeCheck", t: "DSGVO-konform", d: "Datenverarbeitung gemäß der EU-Verordnung." },
      { icon: "Lock", t: "Verschlüsseltes HTTPS", d: "Daten werden stets über eine sichere Verbindung übertragen." },
      { icon: "Server", t: "Server in der EU", d: "Die Verarbeitung erfolgt auf Infrastruktur in der EU." },
    ],
  },
  fr: {
    benefits: [
      { icon: "Clock", t: "Gagnez du temps", d: "Vérifiez en secondes ce qui prendrait des minutes de lecture manuelle." },
      { icon: "AlertTriangle", t: "Moins d'erreurs", d: "L'IA vérifie les rapprochements et la cohérence des données pour vous." },
      { icon: "Search", t: "Repérez les anomalies", d: "Risques, clauses et incohérences mis en évidence automatiquement." },
      { icon: "Rocket", t: "Plus de productivité", d: "Un contrôle documentaire rapide, reproductible et fiable." },
    ],
    how: [
      { n: "01", icon: "Upload", t: "Importez", d: "Importez votre document (PDF, JPG ou PNG)." },
      { n: "02", icon: "Zap", t: "Analysez", d: "L'intelligence artificielle analyse automatiquement le contenu." },
      { n: "03", icon: "Search", t: "Découvrez", d: "Visualisez données, anomalies, informations clés et risques éventuels." },
      { n: "04", icon: "Rocket", t: "Agissez", d: "Exportez les résultats, utilisez le Copilot ou approfondissez l'analyse." },
    ],
    rfFinds: ["Anomalies et incohérences", "Clauses problématiques", "IBAN étrangers suspects", "Écarts sur les montants", "Échéances et préavis critiques", "Éléments de risque à examiner"],
    copExamples: ["Quel est le montant total ?", "Y a-t-il des anomalies ?", "Quelles sont les clauses les plus importantes ?", "Trouve l'IBAN.", "Résume ce document.", "Quels éléments dois-je vérifier ?"],
    docs: [
      { key: "fattura", t: "Factures", d: "Données, montants, TVA et anomalies éventuelles extraits automatiquement." },
      { key: "f24", t: "Formulaires fiscaux", d: "Codes, échéances et rapprochement Débit/Crédit/Solde." },
      { key: "contratto", t: "Contrats", d: "Clauses, parties, durée et éléments à examiner." },
      { key: "visura", t: "Extraits Kbis", d: "Données d'immatriculation, associés, dirigeants et AML/KYC." },
      { key: "busta_paga", t: "Bulletins de paie", d: "Brut, cotisations, impôt, net et indemnités acquises." },
      { key: "altri", t: "Autres documents", d: "Extraction de données et audit sur documents génériques aussi." },
    ],
    sectors: [
      { slug: "commercialisti", icon: "Landmark", t: "Experts-comptables", d: "Vérifiez factures, formulaires et extraits en secondes, sans saisie manuelle." },
      { slug: "avvocati", icon: "Scale", t: "Avocats", d: "Repérez rapidement clauses, échéances et points sensibles des contrats." },
      { slug: "notai", icon: "FileSignature", t: "Notaires", d: "Extrayez les données de société et vérifiez les documents en un instant." },
      { slug: "cfo", icon: "TrendingUp", t: "CFO & Finance", d: "Vérifiez montants, rapprochements et cohérence des données comptables." },
      { slug: "hr", icon: "Users", t: "RH", d: "Analysez bulletins de paie et documents du personnel en secondes." },
      { slug: "aziende", icon: "Briefcase", t: "Entreprises & Pros", d: "Automatisez le contrôle de chaque document que vous gérez." },
    ],
    security: [
      { icon: "Ban", t: "Aucun document stocké", d: "Les fichiers ne sont pas conservés sur nos serveurs." },
      { icon: "Zap", t: "Traitement en temps réel", d: "Chaque document est analysé à la volée, sans archivage." },
      { icon: "Trash2", t: "Suppression immédiate", d: "Le fichier est supprimé dès la fin de l'analyse." },
      { icon: "BadgeCheck", t: "Conforme au RGPD", d: "Traitement des données conforme au règlement européen." },
      { icon: "Lock", t: "HTTPS chiffré", d: "Les données transitent toujours par une connexion sécurisée." },
      { icon: "Server", t: "Serveurs dans l'UE", d: "Le traitement se fait sur une infrastructure dans l'UE." },
    ],
  },
};

/* ---- Sector landing pages (Phase 2): /commercialisti /avvocati /notai /cfo /hr ---- */
export const SECTORS = {
  it: {
    commercialisti: {
      meta_title: "AI per Commercialisti — Analisi automatica di fatture, F24 e visure | DocuAnalytics",
      meta_desc: "Analizza fatture, F24 e visure con l'AI: estrazione dati, quadrature e red-flag automatici. Prova gratis con 3 crediti, senza carta.",
      problem: "Quanto tempo perdi ogni mese a controllare manualmente fatture, F24 e visure?",
      solution: "Lascia che l'AI legga i documenti al posto tuo: estrae i dati, verifica le quadrature e segnala subito anomalie e IBAN sospetti.",
      useCases: ["Controllo massivo di fatture attive e passive", "Quadratura F24 e verifica scadenze fiscali", "Estrazione dati societari dalle visure", "Preparazione dati per la contabilità e i controlli antiriciclaggio"],
      benefits: ["Meno inserimenti manuali e meno errori", "Quadrature verificate automaticamente", "Chiusure di fine mese più rapide", "Red-flag automatico su importi, IBAN e scadenze"],
      example: "Carichi un F24: DocuAnalytics estrae codici tributo e importi e verifica la quadratura Debito / Credito / Saldo in pochi secondi.",
    },
    avvocati: {
      meta_title: "AI per Avvocati — Analisi contratti e clausole | DocuAnalytics",
      meta_desc: "Analizza contratti con l'AI: individua clausole, scadenze e criticità in pochi secondi. Prova gratis con 3 crediti, senza carta.",
      problem: "Quanto tempo richiede leggere e analizzare un contratto riga per riga?",
      solution: "L'AI legge il contratto e mette subito in evidenza parti, durata, clausole rilevanti e possibili criticità da approfondire.",
      useCases: ["Revisione rapida di contratti e accordi", "Individuazione di clausole vessatorie o rischiose", "Estrazione di parti, date e scadenze chiave", "Confronto e riassunto di documenti lunghi"],
      benefits: ["Prima lettura del contratto in pochi secondi", "Meno rischio di trascurare una clausola", "Sintesi immediata dei punti importanti", "Domande dirette al documento con il Copilot"],
      example: "Carichi un contratto: DocuAnalytics riassume le clausole principali ed evidenzia i punti che meritano attenzione.",
    },
    notai: {
      meta_title: "AI per Notai — Verifica visure e dati societari | DocuAnalytics",
      meta_desc: "Estrai e verifica dati societari, visure e documenti con l'AI in pochi secondi. Prova gratis con 3 crediti, senza carta.",
      problem: "Verificare visure e dati societari a mano è lento e ripetitivo.",
      solution: "L'AI estrae i dati salienti da visure e documenti e li presenta in modo strutturato, pronti per il controllo.",
      useCases: ["Estrazione dati da visure camerali", "Verifica di soci, amministratori e cariche", "Controllo di dati anagrafici e societari", "Preparazione documentale per gli atti"],
      benefits: ["Dati societari estratti automaticamente", "Meno tempo sulla lettura manuale", "Controlli più affidabili e ripetibili", "Tutto strutturato e pronto all'uso"],
      example: "Carichi una visura: DocuAnalytics estrae REA, soci e amministratori e prepara i dati per la verifica.",
    },
    cfo: {
      meta_title: "AI per CFO e Finance — Controllo dati contabili | DocuAnalytics",
      meta_desc: "Verifica importi, quadrature e coerenza dei dati contabili con l'AI. Prova gratis con 3 crediti, senza carta.",
      problem: "Controllare importi e coerenza dei dati contabili tra tanti documenti è oneroso.",
      solution: "L'AI verifica importi, quadrature e coerenza dei dati, segnalando subito squadrature e anomalie.",
      useCases: ["Verifica di importi e quadrature", "Controllo di coerenza tra documenti", "Estrazione dati per il reporting", "Individuazione di anomalie e rischi"],
      benefits: ["Controlli finanziari più rapidi", "Anomalie evidenziate automaticamente", "Meno errori nei dati", "Reporting più veloce e affidabile"],
      example: "Carichi una fattura: DocuAnalytics estrae importi e IVA e verifica la coerenza con i dati attesi.",
    },
    hr: {
      meta_title: "AI per HR — Analisi buste paga e documenti del personale | DocuAnalytics",
      meta_desc: "Analizza buste paga e documenti HR con l'AI: estrazione dati in pochi secondi. Prova gratis con 3 crediti, senza carta.",
      problem: "Controllare tante buste paga e documenti del personale a mano richiede molto tempo.",
      solution: "L'AI estrae e organizza le informazioni principali da buste paga e documenti HR in pochi secondi.",
      useCases: ["Analisi di buste paga", "Estrazione di lordo, contributi, IRPEF e netto", "Controllo di documenti del personale", "Preparazione dati per l'amministrazione"],
      benefits: ["Meno tempo sui controlli manuali", "Dati estratti in modo uniforme", "Meno errori di trascrizione", "Flusso di controllo ripetibile"],
      example: "Carichi una busta paga: DocuAnalytics estrae lordo, contributi, IRPEF, netto e TFR maturato.",
    },
  },
  en: {
    commercialisti: {
      meta_title: "AI for Accountants — Automatic invoice, tax-form and record analysis | DocuAnalytics",
      meta_desc: "Analyze invoices, tax forms and company records with AI: data extraction, reconciliations and automatic red-flags. Try free with 3 credits, no card.",
      problem: "How much time do you lose every month manually checking invoices, tax forms and records?",
      solution: "Let AI read the documents for you: it extracts data, verifies reconciliations and instantly flags anomalies and suspicious IBANs.",
      useCases: ["Bulk checking of incoming and outgoing invoices", "Tax-form reconciliation and deadline checks", "Company data extraction from records", "Data prep for accounting and AML checks"],
      benefits: ["Fewer manual entries and fewer errors", "Reconciliations verified automatically", "Faster month-end closings", "Automatic red-flags on amounts, IBAN and deadlines"],
      example: "Upload a tax form: DocuAnalytics extracts codes and amounts and verifies the Debit / Credit / Balance reconciliation in seconds.",
    },
    avvocati: {
      meta_title: "AI for Lawyers — Contract and clause analysis | DocuAnalytics",
      meta_desc: "Analyze contracts with AI: spot clauses, deadlines and issues in seconds. Try free with 3 credits, no card.",
      problem: "How long does it take to read and analyze a contract line by line?",
      solution: "AI reads the contract and instantly highlights parties, term, key clauses and possible issues to review.",
      useCases: ["Fast review of contracts and agreements", "Detection of unfair or risky clauses", "Extraction of parties, dates and key deadlines", "Comparing and summarizing long documents"],
      benefits: ["First read of the contract in seconds", "Less risk of missing a clause", "Instant summary of the key points", "Ask the document directly with Copilot"],
      example: "Upload a contract: DocuAnalytics summarizes the main clauses and highlights the points that deserve attention.",
    },
    notai: {
      meta_title: "AI for Notaries — Record and company-data verification | DocuAnalytics",
      meta_desc: "Extract and verify company data, records and documents with AI in seconds. Try free with 3 credits, no card.",
      problem: "Verifying records and company data by hand is slow and repetitive.",
      solution: "AI extracts the salient data from records and documents and presents it in a structured, ready-to-check way.",
      useCases: ["Data extraction from company records", "Verification of shareholders, directors and roles", "Checking personal and company data", "Document prep for deeds"],
      benefits: ["Company data extracted automatically", "Less time on manual reading", "More reliable, repeatable checks", "Everything structured and ready to use"],
      example: "Upload a company record: DocuAnalytics extracts registration, shareholders and directors and prepares the data for verification.",
    },
    cfo: {
      meta_title: "AI for CFO & Finance — Accounting-data control | DocuAnalytics",
      meta_desc: "Verify amounts, reconciliations and accounting-data consistency with AI. Try free with 3 credits, no card.",
      problem: "Checking amounts and data consistency across many documents is costly.",
      solution: "AI verifies amounts, reconciliations and data consistency, instantly flagging mismatches and anomalies.",
      useCases: ["Verification of amounts and reconciliations", "Consistency checks across documents", "Data extraction for reporting", "Detection of anomalies and risks"],
      benefits: ["Faster financial checks", "Anomalies highlighted automatically", "Fewer data errors", "Faster, more reliable reporting"],
      example: "Upload an invoice: DocuAnalytics extracts amounts and VAT and checks consistency with the expected data.",
    },
    hr: {
      meta_title: "AI for HR — Payslip and personnel-document analysis | DocuAnalytics",
      meta_desc: "Analyze payslips and HR documents with AI: data extraction in seconds. Try free with 3 credits, no card.",
      problem: "Checking many payslips and personnel documents by hand takes a lot of time.",
      solution: "AI extracts and organizes the key information from payslips and HR documents in seconds.",
      useCases: ["Payslip analysis", "Extraction of gross, contributions, tax and net", "Checking personnel documents", "Data prep for administration"],
      benefits: ["Less time on manual checks", "Data extracted uniformly", "Fewer transcription errors", "A repeatable checking workflow"],
      example: "Upload a payslip: DocuAnalytics extracts gross, contributions, tax, net and accrued severance.",
    },
  },
  es: {
    commercialisti: {
      meta_title: "IA para Asesores — Análisis automático de facturas y modelos | DocuAnalytics",
      meta_desc: "Analiza facturas, modelos y registros con IA: extracción de datos, cuadres y alertas automáticas. Prueba gratis con 3 créditos, sin tarjeta.",
      problem: "¿Cuánto tiempo pierdes cada mes revisando manualmente facturas, modelos y registros?",
      solution: "Deja que la IA lea los documentos por ti: extrae los datos, verifica los cuadres y señala al instante anomalías e IBAN sospechosos.",
      useCases: ["Revisión masiva de facturas emitidas y recibidas", "Cuadre de modelos y control de vencimientos", "Extracción de datos societarios de los registros", "Preparación de datos para contabilidad y AML"],
      benefits: ["Menos entradas manuales y menos errores", "Cuadres verificados automáticamente", "Cierres de mes más rápidos", "Alertas automáticas de importes, IBAN y vencimientos"],
      example: "Sube un modelo fiscal: DocuAnalytics extrae códigos e importes y verifica el cuadre Debe / Haber / Saldo en segundos.",
    },
    avvocati: {
      meta_title: "IA para Abogados — Análisis de contratos y cláusulas | DocuAnalytics",
      meta_desc: "Analiza contratos con IA: detecta cláusulas, plazos y problemas en segundos. Prueba gratis con 3 créditos, sin tarjeta.",
      problem: "¿Cuánto se tarda en leer y analizar un contrato línea por línea?",
      solution: "La IA lee el contrato y resalta al instante partes, duración, cláusulas clave y posibles problemas a revisar.",
      useCases: ["Revisión rápida de contratos y acuerdos", "Detección de cláusulas abusivas o de riesgo", "Extracción de partes, fechas y plazos clave", "Comparar y resumir documentos largos"],
      benefits: ["Primera lectura del contrato en segundos", "Menos riesgo de pasar por alto una cláusula", "Resumen inmediato de los puntos clave", "Pregunta al documento con el Copilot"],
      example: "Sube un contrato: DocuAnalytics resume las cláusulas principales y resalta los puntos que merecen atención.",
    },
    notai: {
      meta_title: "IA para Notarios — Verificación de registros y datos | DocuAnalytics",
      meta_desc: "Extrae y verifica datos societarios y documentos con IA en segundos. Prueba gratis con 3 créditos, sin tarjeta.",
      problem: "Verificar registros y datos societarios a mano es lento y repetitivo.",
      solution: "La IA extrae los datos relevantes de registros y documentos y los presenta de forma estructurada, listos para revisar.",
      useCases: ["Extracción de datos de registros mercantiles", "Verificación de socios, administradores y cargos", "Control de datos personales y societarios", "Preparación documental para las escrituras"],
      benefits: ["Datos societarios extraídos automáticamente", "Menos tiempo de lectura manual", "Controles más fiables y repetibles", "Todo estructurado y listo para usar"],
      example: "Sube un registro: DocuAnalytics extrae datos de inscripción, socios y administradores y los prepara para la verificación.",
    },
    cfo: {
      meta_title: "IA para CFO y Finanzas — Control de datos contables | DocuAnalytics",
      meta_desc: "Verifica importes, cuadres y coherencia de los datos contables con IA. Prueba gratis con 3 créditos, sin tarjeta.",
      problem: "Revisar importes y coherencia de datos entre muchos documentos es costoso.",
      solution: "La IA verifica importes, cuadres y coherencia de los datos, señalando al instante descuadres y anomalías.",
      useCases: ["Verificación de importes y cuadres", "Controles de coherencia entre documentos", "Extracción de datos para el reporting", "Detección de anomalías y riesgos"],
      benefits: ["Controles financieros más rápidos", "Anomalías resaltadas automáticamente", "Menos errores en los datos", "Reporting más rápido y fiable"],
      example: "Sube una factura: DocuAnalytics extrae importes e IVA y comprueba la coherencia con los datos esperados.",
    },
    hr: {
      meta_title: "IA para RR. HH. — Análisis de nóminas y documentos | DocuAnalytics",
      meta_desc: "Analiza nóminas y documentos de RR. HH. con IA: extracción de datos en segundos. Prueba gratis con 3 créditos, sin tarjeta.",
      problem: "Revisar muchas nóminas y documentos del personal a mano lleva mucho tiempo.",
      solution: "La IA extrae y organiza la información clave de nóminas y documentos de RR. HH. en segundos.",
      useCases: ["Análisis de nóminas", "Extracción de bruto, cotizaciones, IRPF y neto", "Control de documentos del personal", "Preparación de datos para administración"],
      benefits: ["Menos tiempo en controles manuales", "Datos extraídos de forma uniforme", "Menos errores de transcripción", "Un flujo de control repetible"],
      example: "Sube una nómina: DocuAnalytics extrae bruto, cotizaciones, IRPF, neto y finiquito acumulado.",
    },
  },
  de: {
    commercialisti: {
      meta_title: "KI für Steuerberater — Automatische Rechnungs- und Formularanalyse | DocuAnalytics",
      meta_desc: "Analysieren Sie Rechnungen, Steuerformulare und Auszüge mit KI: Datenextraktion, Abgleiche und automatische Red-Flags. Kostenlos testen mit 3 Guthaben, ohne Karte.",
      problem: "Wie viel Zeit verlieren Sie jeden Monat mit der manuellen Prüfung von Rechnungen, Formularen und Auszügen?",
      solution: "Lassen Sie die KI die Dokumente für Sie lesen: Sie extrahiert Daten, prüft Abgleiche und meldet sofort Anomalien und verdächtige IBANs.",
      useCases: ["Massenprüfung ein- und ausgehender Rechnungen", "Formular-Abgleich und Fristenkontrolle", "Extraktion von Gesellschaftsdaten aus Auszügen", "Datenaufbereitung für Buchhaltung und AML"],
      benefits: ["Weniger manuelle Eingaben und Fehler", "Abgleiche automatisch geprüft", "Schnellere Monatsabschlüsse", "Automatische Red-Flags bei Beträgen, IBAN und Fristen"],
      example: "Laden Sie ein Steuerformular hoch: DocuAnalytics extrahiert Codes und Beträge und prüft den Soll / Haben / Saldo-Abgleich in Sekunden.",
    },
    avvocati: {
      meta_title: "KI für Anwälte — Vertrags- und Klauselanalyse | DocuAnalytics",
      meta_desc: "Analysieren Sie Verträge mit KI: Klauseln, Fristen und Probleme in Sekunden erkennen. Kostenlos testen mit 3 Guthaben, ohne Karte.",
      problem: "Wie lange dauert es, einen Vertrag Zeile für Zeile zu lesen und zu analysieren?",
      solution: "Die KI liest den Vertrag und hebt sofort Parteien, Laufzeit, wichtige Klauseln und mögliche Probleme hervor.",
      useCases: ["Schnelle Prüfung von Verträgen und Vereinbarungen", "Erkennung unfairer oder riskanter Klauseln", "Extraktion von Parteien, Daten und Fristen", "Vergleichen und Zusammenfassen langer Dokumente"],
      benefits: ["Erste Lektüre des Vertrags in Sekunden", "Geringeres Risiko, eine Klausel zu übersehen", "Sofortige Zusammenfassung der wichtigsten Punkte", "Fragen Sie das Dokument direkt mit dem Copilot"],
      example: "Laden Sie einen Vertrag hoch: DocuAnalytics fasst die wichtigsten Klauseln zusammen und hebt beachtenswerte Punkte hervor.",
    },
    notai: {
      meta_title: "KI für Notare — Prüfung von Auszügen und Gesellschaftsdaten | DocuAnalytics",
      meta_desc: "Extrahieren und prüfen Sie Gesellschaftsdaten und Dokumente mit KI in Sekunden. Kostenlos testen mit 3 Guthaben, ohne Karte.",
      problem: "Auszüge und Gesellschaftsdaten von Hand zu prüfen ist langsam und repetitiv.",
      solution: "Die KI extrahiert die wesentlichen Daten aus Auszügen und Dokumenten und stellt sie strukturiert und prüfbereit dar.",
      useCases: ["Datenextraktion aus Registerauszügen", "Prüfung von Gesellschaftern, Geschäftsführern und Rollen", "Kontrolle von Personen- und Gesellschaftsdaten", "Dokumentvorbereitung für Urkunden"],
      benefits: ["Gesellschaftsdaten automatisch extrahiert", "Weniger Zeit für manuelles Lesen", "Zuverlässigere, wiederholbare Prüfungen", "Alles strukturiert und einsatzbereit"],
      example: "Laden Sie einen Auszug hoch: DocuAnalytics extrahiert Registerdaten, Gesellschafter und Geschäftsführer und bereitet sie zur Prüfung auf.",
    },
    cfo: {
      meta_title: "KI für CFO & Finance — Kontrolle der Buchhaltungsdaten | DocuAnalytics",
      meta_desc: "Prüfen Sie Beträge, Abgleiche und Konsistenz der Buchhaltungsdaten mit KI. Kostenlos testen mit 3 Guthaben, ohne Karte.",
      problem: "Beträge und Datenkonsistenz über viele Dokumente hinweg zu prüfen ist aufwendig.",
      solution: "Die KI prüft Beträge, Abgleiche und Datenkonsistenz und meldet sofort Abweichungen und Anomalien.",
      useCases: ["Prüfung von Beträgen und Abgleichen", "Konsistenzprüfungen über Dokumente hinweg", "Datenextraktion für das Reporting", "Erkennung von Anomalien und Risiken"],
      benefits: ["Schnellere Finanzprüfungen", "Anomalien automatisch hervorgehoben", "Weniger Datenfehler", "Schnelleres, zuverlässigeres Reporting"],
      example: "Laden Sie eine Rechnung hoch: DocuAnalytics extrahiert Beträge und USt. und prüft die Konsistenz mit den erwarteten Daten.",
    },
    hr: {
      meta_title: "KI für HR — Analyse von Abrechnungen und Personaldokumenten | DocuAnalytics",
      meta_desc: "Analysieren Sie Gehaltsabrechnungen und HR-Dokumente mit KI: Datenextraktion in Sekunden. Kostenlos testen mit 3 Guthaben, ohne Karte.",
      problem: "Viele Abrechnungen und Personaldokumente von Hand zu prüfen kostet viel Zeit.",
      solution: "Die KI extrahiert und ordnet die wichtigsten Informationen aus Abrechnungen und HR-Dokumenten in Sekunden.",
      useCases: ["Analyse von Gehaltsabrechnungen", "Extraktion von Brutto, Beiträgen, Steuer und Netto", "Kontrolle von Personaldokumenten", "Datenaufbereitung für die Verwaltung"],
      benefits: ["Weniger Zeit für manuelle Kontrollen", "Daten einheitlich extrahiert", "Weniger Übertragungsfehler", "Ein wiederholbarer Prüf-Workflow"],
      example: "Laden Sie eine Abrechnung hoch: DocuAnalytics extrahiert Brutto, Beiträge, Steuer, Netto und aufgelaufene Abfindung.",
    },
  },
  fr: {
    commercialisti: {
      meta_title: "IA pour Experts-comptables — Analyse automatique de factures et formulaires | DocuAnalytics",
      meta_desc: "Analysez factures, formulaires et extraits avec l'IA : extraction de données, rapprochements et alertes automatiques. Essai gratuit avec 3 crédits, sans carte.",
      problem: "Combien de temps perdez-vous chaque mois à vérifier manuellement factures, formulaires et extraits ?",
      solution: "Laissez l'IA lire les documents à votre place : elle extrait les données, vérifie les rapprochements et signale aussitôt anomalies et IBAN suspects.",
      useCases: ["Vérification en masse des factures émises et reçues", "Rapprochement des formulaires et contrôle des échéances", "Extraction des données de société depuis les extraits", "Préparation des données pour la comptabilité et l'AML"],
      benefits: ["Moins de saisies manuelles et d'erreurs", "Rapprochements vérifiés automatiquement", "Clôtures de fin de mois plus rapides", "Alertes automatiques sur montants, IBAN et échéances"],
      example: "Importez un formulaire fiscal : DocuAnalytics extrait codes et montants et vérifie le rapprochement Débit / Crédit / Solde en quelques secondes.",
    },
    avvocati: {
      meta_title: "IA pour Avocats — Analyse de contrats et de clauses | DocuAnalytics",
      meta_desc: "Analysez des contrats avec l'IA : repérez clauses, échéances et points sensibles en quelques secondes. Essai gratuit avec 3 crédits, sans carte.",
      problem: "Combien de temps faut-il pour lire et analyser un contrat ligne par ligne ?",
      solution: "L'IA lit le contrat et met aussitôt en évidence parties, durée, clauses clés et points sensibles à examiner.",
      useCases: ["Revue rapide de contrats et d'accords", "Détection de clauses abusives ou risquées", "Extraction des parties, dates et échéances clés", "Comparer et résumer de longs documents"],
      benefits: ["Première lecture du contrat en quelques secondes", "Moins de risque d'oublier une clause", "Résumé immédiat des points clés", "Interrogez le document avec le Copilot"],
      example: "Importez un contrat : DocuAnalytics résume les principales clauses et met en évidence les points qui méritent attention.",
    },
    notai: {
      meta_title: "IA pour Notaires — Vérification d'extraits et de données | DocuAnalytics",
      meta_desc: "Extrayez et vérifiez données de société et documents avec l'IA en quelques secondes. Essai gratuit avec 3 crédits, sans carte.",
      problem: "Vérifier extraits et données de société à la main est lent et répétitif.",
      solution: "L'IA extrait les données essentielles des extraits et documents et les présente de façon structurée, prêtes à vérifier.",
      useCases: ["Extraction de données d'extraits Kbis", "Vérification des associés, dirigeants et fonctions", "Contrôle des données personnelles et de société", "Préparation documentaire pour les actes"],
      benefits: ["Données de société extraites automatiquement", "Moins de temps de lecture manuelle", "Contrôles plus fiables et reproductibles", "Tout structuré et prêt à l'emploi"],
      example: "Importez un extrait : DocuAnalytics extrait les données d'immatriculation, associés et dirigeants et les prépare pour la vérification.",
    },
    cfo: {
      meta_title: "IA pour CFO & Finance — Contrôle des données comptables | DocuAnalytics",
      meta_desc: "Vérifiez montants, rapprochements et cohérence des données comptables avec l'IA. Essai gratuit avec 3 crédits, sans carte.",
      problem: "Vérifier montants et cohérence des données sur de nombreux documents est coûteux.",
      solution: "L'IA vérifie montants, rapprochements et cohérence des données, en signalant aussitôt écarts et anomalies.",
      useCases: ["Vérification des montants et rapprochements", "Contrôles de cohérence entre documents", "Extraction de données pour le reporting", "Détection d'anomalies et de risques"],
      benefits: ["Contrôles financiers plus rapides", "Anomalies mises en évidence automatiquement", "Moins d'erreurs de données", "Reporting plus rapide et fiable"],
      example: "Importez une facture : DocuAnalytics extrait montants et TVA et vérifie la cohérence avec les données attendues.",
    },
    hr: {
      meta_title: "IA pour RH — Analyse de bulletins de paie et documents | DocuAnalytics",
      meta_desc: "Analysez bulletins de paie et documents RH avec l'IA : extraction de données en quelques secondes. Essai gratuit avec 3 crédits, sans carte.",
      problem: "Vérifier de nombreux bulletins de paie et documents du personnel à la main prend beaucoup de temps.",
      solution: "L'IA extrait et organise les informations clés des bulletins de paie et documents RH en quelques secondes.",
      useCases: ["Analyse de bulletins de paie", "Extraction du brut, cotisations, impôt et net", "Contrôle des documents du personnel", "Préparation des données pour l'administration"],
      benefits: ["Moins de temps sur les contrôles manuels", "Données extraites de façon uniforme", "Moins d'erreurs de saisie", "Un contrôle reproductible"],
      example: "Importez un bulletin de paie : DocuAnalytics extrait le brut, les cotisations, l'impôt, le net et les indemnités acquises.",
    },
  },
};


/* ---- Hero animated demo (fictitious data, labelled). 3 rotating documents. ---- */
export const DEMO = {
  it: { analyze: "Analizza un documento", credits: "Crediti disponibili", newTtl: "Nuova analisi", newSub: "Carica un documento per iniziare", drop: "Trascina qui il documento", or: "oppure selezionalo dal dispositivo", pRead: "Lettura documento…", pExtract: "Estrazione dati…", pCheck: "Controllo anomalie…", result: "Risultato analisi", resultSub: "Informazioni estratte dal documento", waiting: "In attesa", done: "Analisi completata", caption: "Demo animata — dati completamente fittizi", nav: ["Dashboard", "Analizza", "Copilot", "Red-Flag AI", "Documenti"],
    variants: [
      { title: "FATTURA — ESEMPIO", headline: "€ 1.240,00", items: [["Importo totale", "€ 1.240,00"], ["Data documento", "28/08/2026"], ["Dati fiscali", "Completi"]], flag: "Red-Flag AI — da verificare", flagP: "IBAN estero rilevato: consigliato un controllo." },
      { title: "CONTRATTO — ESEMPIO", headline: "24 mesi", items: [["Parti individuate", "2"], ["Durata", "24 mesi"], ["Clausole rilevate", "12"]], flag: "Red-Flag AI — da verificare", flagP: "Clausola di rinnovo tacito da valutare." },
      { title: "BUSTA PAGA — ESEMPIO", headline: "€ 1.850,00", items: [["Retribuzione lorda", "€ 2.400,00"], ["Netto in busta", "€ 1.850,00"], ["Contributi/IRPEF", "Estratti"]], flag: "Red-Flag AI — da verificare", flagP: "Voce fuori standard: merita un controllo." },
    ] },
  en: { analyze: "Analyze a document", credits: "Available credits", newTtl: "New analysis", newSub: "Upload a document to start", drop: "Drop your document here", or: "or select it from your device", pRead: "Reading document…", pExtract: "Extracting data…", pCheck: "Checking anomalies…", result: "Analysis result", resultSub: "Information extracted from the document", waiting: "Waiting", done: "Analysis complete", caption: "Animated demo — entirely fictitious data", nav: ["Dashboard", "Analyze", "Copilot", "Red-Flag AI", "Documents"],
    variants: [
      { title: "INVOICE — SAMPLE", headline: "€ 1,240.00", items: [["Total amount", "€ 1,240.00"], ["Document date", "08/28/2026"], ["Tax data", "Complete"]], flag: "Red-Flag AI — to review", flagP: "Foreign IBAN detected: a check is recommended." },
      { title: "CONTRACT — SAMPLE", headline: "24 months", items: [["Parties found", "2"], ["Term", "24 months"], ["Clauses detected", "12"]], flag: "Red-Flag AI — to review", flagP: "Auto-renewal clause worth reviewing." },
      { title: "PAYSLIP — SAMPLE", headline: "€ 1,850.00", items: [["Gross pay", "€ 2,400.00"], ["Net pay", "€ 1,850.00"], ["Contributions/Tax", "Extracted"]], flag: "Red-Flag AI — to review", flagP: "Non-standard item: worth a check." },
    ] },
  es: { analyze: "Analiza un documento", credits: "Créditos disponibles", newTtl: "Nuevo análisis", newSub: "Sube un documento para empezar", drop: "Arrastra aquí el documento", or: "o selecciónalo desde tu dispositivo", pRead: "Leyendo documento…", pExtract: "Extrayendo datos…", pCheck: "Comprobando anomalías…", result: "Resultado del análisis", resultSub: "Información extraída del documento", waiting: "En espera", done: "Análisis completado", caption: "Demo animada — datos totalmente ficticios", nav: ["Panel", "Analizar", "Copilot", "Alertas IA", "Documentos"],
    variants: [
      { title: "FACTURA — EJEMPLO", headline: "€ 1.240,00", items: [["Importe total", "€ 1.240,00"], ["Fecha del documento", "28/08/2026"], ["Datos fiscales", "Completos"]], flag: "Alertas IA — a revisar", flagP: "IBAN extranjero detectado: se recomienda revisar." },
      { title: "CONTRATO — EJEMPLO", headline: "24 meses", items: [["Partes identificadas", "2"], ["Duración", "24 meses"], ["Cláusulas detectadas", "12"]], flag: "Alertas IA — a revisar", flagP: "Cláusula de renovación tácita a valorar." },
      { title: "NÓMINA — EJEMPLO", headline: "€ 1.850,00", items: [["Salario bruto", "€ 2.400,00"], ["Neto", "€ 1.850,00"], ["Cotizaciones/IRPF", "Extraídos"]], flag: "Alertas IA — a revisar", flagP: "Concepto fuera de lo estándar: conviene revisar." },
    ] },
  de: { analyze: "Ein Dokument analysieren", credits: "Verfügbares Guthaben", newTtl: "Neue Analyse", newSub: "Laden Sie ein Dokument hoch, um zu starten", drop: "Dokument hier ablegen", or: "oder vom Gerät auswählen", pRead: "Dokument wird gelesen…", pExtract: "Daten werden extrahiert…", pCheck: "Anomalien werden geprüft…", result: "Analyseergebnis", resultSub: "Aus dem Dokument extrahierte Informationen", waiting: "Wartet", done: "Analyse abgeschlossen", caption: "Animierte Demo — vollständig fiktive Daten", nav: ["Dashboard", "Analysieren", "Copilot", "Red-Flag KI", "Dokumente"],
    variants: [
      { title: "RECHNUNG — BEISPIEL", headline: "€ 1.240,00", items: [["Gesamtbetrag", "€ 1.240,00"], ["Belegdatum", "28.08.2026"], ["Steuerdaten", "Vollständig"]], flag: "Red-Flag KI — prüfen", flagP: "Ausländische IBAN erkannt: Prüfung empfohlen." },
      { title: "VERTRAG — BEISPIEL", headline: "24 Monate", items: [["Parteien erkannt", "2"], ["Laufzeit", "24 Monate"], ["Klauseln erkannt", "12"]], flag: "Red-Flag KI — prüfen", flagP: "Klausel zur automatischen Verlängerung prüfen." },
      { title: "ABRECHNUNG — BEISPIEL", headline: "€ 1.850,00", items: [["Bruttolohn", "€ 2.400,00"], ["Nettolohn", "€ 1.850,00"], ["Beiträge/Steuer", "Extrahiert"]], flag: "Red-Flag KI — prüfen", flagP: "Nicht-standardmäßige Position: prüfenswert." },
    ] },
  fr: { analyze: "Analyser un document", credits: "Crédits disponibles", newTtl: "Nouvelle analyse", newSub: "Importez un document pour commencer", drop: "Déposez votre document ici", or: "ou sélectionnez-le depuis votre appareil", pRead: "Lecture du document…", pExtract: "Extraction des données…", pCheck: "Contrôle des anomalies…", result: "Résultat de l'analyse", resultSub: "Informations extraites du document", waiting: "En attente", done: "Analyse terminée", caption: "Démo animée — données entièrement fictives", nav: ["Tableau de bord", "Analyser", "Copilot", "Alertes IA", "Documents"],
    variants: [
      { title: "FACTURE — EXEMPLE", headline: "€ 1 240,00", items: [["Montant total", "€ 1 240,00"], ["Date du document", "28/08/2026"], ["Données fiscales", "Complètes"]], flag: "Alertes IA — à vérifier", flagP: "IBAN étranger détecté : vérification conseillée." },
      { title: "CONTRAT — EXEMPLE", headline: "24 mois", items: [["Parties identifiées", "2"], ["Durée", "24 mois"], ["Clauses détectées", "12"]], flag: "Alertes IA — à vérifier", flagP: "Clause de reconduction tacite à examiner." },
      { title: "BULLETIN DE PAIE — EXEMPLE", headline: "€ 1 850,00", items: [["Salaire brut", "€ 2 400,00"], ["Net à payer", "€ 1 850,00"], ["Cotisations/Impôt", "Extraits"]], flag: "Alertes IA — à vérifier", flagP: "Élément non standard : à vérifier." },
    ] },
};

